import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Layout from '@/components/layout';
import { getAllproducts } from '@/utils/products';
import Card from '@/components/card';

export default function Home({productData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <p>
            i prodotti
          </p>
          {productData?.map((prod)=>(
            <Card key={prod.id} prod={prod}/>
          ))}
        </Layout>
      </main>
    </>
  )
}

export const getStaticProps=()=>{
  const productData = getAllproducts();
  return{
    props:{
      productData,
    },
  }
}
